UsersTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: User-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: EmailId
        AttributeType: S
    KeySchema:
      - AttributeName: EmailId
        KeyType: HASH
